name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World !!!"
      - name: Shut
        run: echo "Shutting down !!!"
      - name: Print Date
        run: echo "Today's Date is $ date +"%A, %b %d, %Y %I:%M %p""
