name: test
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World !!!"
      - name: Shut
        run: echo "Shutting down !!!"
      - name: Print Date
        run: echo Current Date and Time is: `date +"%Y-%m-%d %T"`
